name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Spring Boot application
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Push to Render
        run: docker push my-app
